/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package thrift.test;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ExceptionWithAMap extends org.apache.thrift.TException implements org.apache.thrift.TBase<ExceptionWithAMap, ExceptionWithAMap._Fields>, java.io.Serializable, Cloneable, Comparable<ExceptionWithAMap> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ExceptionWithAMap");

    private static final org.apache.thrift.protocol.TField BLAH_FIELD_DESC = new org.apache.thrift.protocol.TField("blah", org.apache.thrift.protocol.TType.STRING, (short) 1);
    private static final org.apache.thrift.protocol.TField MAP_FIELD_FIELD_DESC = new org.apache.thrift.protocol.TField("map_field", org.apache.thrift.protocol.TType.MAP, (short) 2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ExceptionWithAMapStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ExceptionWithAMapTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable java.lang.String blah; // required
    public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.lang.String> map_field; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        BLAH((short) 1, "blah"),
        MAP_FIELD((short) 2, "map_field");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // BLAH
                    return BLAH;
                case 2: // MAP_FIELD
                    return MAP_FIELD;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId() {
            return _thriftId;
        }

        @Override
        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.BLAH, new org.apache.thrift.meta_data.FieldMetaData("blah", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.MAP_FIELD, new org.apache.thrift.meta_data.FieldMetaData("map_field", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP,
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING),
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ExceptionWithAMap.class, metaDataMap);
    }

    public ExceptionWithAMap() {
    }

    public ExceptionWithAMap(
            java.lang.String blah,
            java.util.Map<java.lang.String, java.lang.String> map_field) {
        this();
        this.blah = blah;
        this.map_field = map_field;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public ExceptionWithAMap(ExceptionWithAMap other) {
        if (other.isSetBlah()) {
            this.blah = other.blah;
        }
        if (other.isSetMap_field()) {
            java.util.Map<java.lang.String, java.lang.String> __this__map_field = new java.util.HashMap<java.lang.String, java.lang.String>(other.map_field);
            this.map_field = __this__map_field;
        }
    }

    @Override
    public ExceptionWithAMap deepCopy() {
        return new ExceptionWithAMap(this);
    }

    @Override
    public void clear() {
        this.blah = null;
        this.map_field = null;
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getBlah() {
        return this.blah;
    }

    public ExceptionWithAMap setBlah(@org.apache.thrift.annotation.Nullable java.lang.String blah) {
        this.blah = blah;
        return this;
    }

    public void unsetBlah() {
        this.blah = null;
    }

    /** Returns true if field blah is set (has been assigned a value) and false otherwise */
    public boolean isSetBlah() {
        return this.blah != null;
    }

    public void setBlahIsSet(boolean value) {
        if (!value) {
            this.blah = null;
        }
    }

    public int getMap_fieldSize() {
        return (this.map_field == null) ? 0 : this.map_field.size();
    }

    public void putToMap_field(java.lang.String key, java.lang.String val) {
        if (this.map_field == null) {
            this.map_field = new java.util.HashMap<java.lang.String, java.lang.String>();
        }
        this.map_field.put(key, val);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Map<java.lang.String, java.lang.String> getMap_field() {
        return this.map_field;
    }

    public ExceptionWithAMap setMap_field(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String, java.lang.String> map_field) {
        this.map_field = map_field;
        return this;
    }

    public void unsetMap_field() {
        this.map_field = null;
    }

    /** Returns true if field map_field is set (has been assigned a value) and false otherwise */
    public boolean isSetMap_field() {
        return this.map_field != null;
    }

    public void setMap_fieldIsSet(boolean value) {
        if (!value) {
            this.map_field = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case BLAH:
                if (value == null) {
                    unsetBlah();
                } else {
                    setBlah((java.lang.String) value);
                }
                break;

            case MAP_FIELD:
                if (value == null) {
                    unsetMap_field();
                } else {
                    setMap_field((java.util.Map<java.lang.String, java.lang.String>) value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case BLAH:
                return getBlah();

            case MAP_FIELD:
                return getMap_field();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case BLAH:
                return isSetBlah();
            case MAP_FIELD:
                return isSetMap_field();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that instanceof ExceptionWithAMap)
            return this.equals((ExceptionWithAMap) that);
        return false;
    }

    public boolean equals(ExceptionWithAMap that) {
        if (that == null)
            return false;
        if (this == that)
            return true;

        boolean this_present_blah = true && this.isSetBlah();
        boolean that_present_blah = true && that.isSetBlah();
        if (this_present_blah || that_present_blah) {
            if (!(this_present_blah && that_present_blah))
                return false;
            if (!this.blah.equals(that.blah))
                return false;
        }

        boolean this_present_map_field = true && this.isSetMap_field();
        boolean that_present_map_field = true && that.isSetMap_field();
        if (this_present_map_field || that_present_map_field) {
            if (!(this_present_map_field && that_present_map_field))
                return false;
            if (!this.map_field.equals(that.map_field))
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetBlah()) ? 131071 : 524287);
        if (isSetBlah())
            hashCode = hashCode * 8191 + blah.hashCode();

        hashCode = hashCode * 8191 + ((isSetMap_field()) ? 131071 : 524287);
        if (isSetMap_field())
            hashCode = hashCode * 8191 + map_field.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(ExceptionWithAMap other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.compare(isSetBlah(), other.isSetBlah());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetBlah()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.blah, other.blah);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetMap_field(), other.isSetMap_field());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetMap_field()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.map_field, other.map_field);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public _Fields[] getFields() {
        return _Fields.values();
    }

    public java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> getFieldMetaData() {
        return metaDataMap;
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("ExceptionWithAMap(");
        boolean first = true;

        sb.append("blah:");
        if (this.blah == null) {
            sb.append("null");
        } else {
            sb.append(this.blah);
        }
        first = false;
        if (!first) sb.append(", ");
        sb.append("map_field:");
        if (this.map_field == null) {
            sb.append("null");
        } else {
            sb.append(this.map_field);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class ExceptionWithAMapStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public ExceptionWithAMapStandardScheme getScheme() {
            return new ExceptionWithAMapStandardScheme();
        }
    }

    private static class ExceptionWithAMapStandardScheme extends org.apache.thrift.scheme.StandardScheme<ExceptionWithAMap> {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, ExceptionWithAMap struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // BLAH
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.blah = iprot.readString();
                            struct.setBlahIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // MAP_FIELD
                        if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                            {
                                org.apache.thrift.protocol.TMap _map500 = iprot.readMapBegin();
                                struct.map_field = new java.util.HashMap<java.lang.String, java.lang.String>(2 * _map500.size);
                                @org.apache.thrift.annotation.Nullable java.lang.String _key501;
                                @org.apache.thrift.annotation.Nullable java.lang.String _val502;
                                for (int _i503 = 0; _i503 < _map500.size; ++_i503) {
                                    _key501 = iprot.readString();
                                    _val502 = iprot.readString();
                                    struct.map_field.put(_key501, _val502);
                                }
                                iprot.readMapEnd();
                            }
                            struct.setMap_fieldIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, ExceptionWithAMap struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.blah != null) {
                oprot.writeFieldBegin(BLAH_FIELD_DESC);
                oprot.writeString(struct.blah);
                oprot.writeFieldEnd();
            }
            if (struct.map_field != null) {
                oprot.writeFieldBegin(MAP_FIELD_FIELD_DESC);
                {
                    oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.map_field.size()));
                    for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter504 : struct.map_field.entrySet()) {
                        oprot.writeString(_iter504.getKey());
                        oprot.writeString(_iter504.getValue());
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class ExceptionWithAMapTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public ExceptionWithAMapTupleScheme getScheme() {
            return new ExceptionWithAMapTupleScheme();
        }
    }

    private static class ExceptionWithAMapTupleScheme extends org.apache.thrift.scheme.TupleScheme<ExceptionWithAMap> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, ExceptionWithAMap struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetBlah()) {
                optionals.set(0);
            }
            if (struct.isSetMap_field()) {
                optionals.set(1);
            }
            oprot.writeBitSet(optionals, 2);
            if (struct.isSetBlah()) {
                oprot.writeString(struct.blah);
            }
            if (struct.isSetMap_field()) {
                {
                    oprot.writeI32(struct.map_field.size());
                    for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter505 : struct.map_field.entrySet()) {
                        oprot.writeString(_iter505.getKey());
                        oprot.writeString(_iter505.getValue());
                    }
                }
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, ExceptionWithAMap struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(2);
            if (incoming.get(0)) {
                struct.blah = iprot.readString();
                struct.setBlahIsSet(true);
            }
            if (incoming.get(1)) {
                {
                    org.apache.thrift.protocol.TMap _map506 = iprot.readMapBegin(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING);
                    struct.map_field = new java.util.HashMap<java.lang.String, java.lang.String>(2 * _map506.size);
                    @org.apache.thrift.annotation.Nullable java.lang.String _key507;
                    @org.apache.thrift.annotation.Nullable java.lang.String _val508;
                    for (int _i509 = 0; _i509 < _map506.size; ++_i509) {
                        _key507 = iprot.readString();
                        _val508 = iprot.readString();
                        struct.map_field.put(_key507, _val508);
                    }
                }
                struct.setMap_fieldIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

