/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package thrift.test;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class Map implements org.apache.thrift.TBase<Map, Map._Fields>, java.io.Serializable, Cloneable, Comparable<Map> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Map");

    private static final org.apache.thrift.protocol.TField VALS_FIELD_DESC = new org.apache.thrift.protocol.TField("vals", org.apache.thrift.protocol.TType.MAP, (short) 1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MapStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MapTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.Double, Double> vals; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        VALS((short) 1, "vals");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // VALS
                    return VALS;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId() {
            return _thriftId;
        }

        @Override
        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.VALS, new org.apache.thrift.meta_data.FieldMetaData("vals", org.apache.thrift.TFieldRequirementType.DEFAULT,
                new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP,
                        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE),
                        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Double.class))));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Map.class, metaDataMap);
    }

    public Map() {
    }

    public Map(
            java.util.Map<java.lang.Double, Double> vals) {
        this();
        this.vals = vals;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public Map(Map other) {
        if (other.isSetVals()) {
            java.util.Map<java.lang.Double, Double> __this__vals = new java.util.HashMap<java.lang.Double, Double>(other.vals.size());
            for (java.util.Map.Entry<java.lang.Double, Double> other_element : other.vals.entrySet()) {

                java.lang.Double other_element_key = other_element.getKey();
                Double other_element_value = other_element.getValue();

                java.lang.Double __this__vals_copy_key = other_element_key;

                Double __this__vals_copy_value = new Double(other_element_value);

                __this__vals.put(__this__vals_copy_key, __this__vals_copy_value);
            }
            this.vals = __this__vals;
        }
    }

    @Override
    public Map deepCopy() {
        return new Map(this);
    }

    @Override
    public void clear() {
        this.vals = null;
    }

    public int getValsSize() {
        return (this.vals == null) ? 0 : this.vals.size();
    }

    public void putToVals(double key, Double val) {
        if (this.vals == null) {
            this.vals = new java.util.HashMap<java.lang.Double, Double>();
        }
        this.vals.put(key, val);
    }

    @org.apache.thrift.annotation.Nullable
    public java.util.Map<java.lang.Double, Double> getVals() {
        return this.vals;
    }

    public Map setVals(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.Double, Double> vals) {
        this.vals = vals;
        return this;
    }

    public void unsetVals() {
        this.vals = null;
    }

    /** Returns true if field vals is set (has been assigned a value) and false otherwise */
    public boolean isSetVals() {
        return this.vals != null;
    }

    public void setValsIsSet(boolean value) {
        if (!value) {
            this.vals = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case VALS:
                if (value == null) {
                    unsetVals();
                } else {
                    setVals((java.util.Map<java.lang.Double, Double>) value);
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case VALS:
                return getVals();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case VALS:
                return isSetVals();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that instanceof Map)
            return this.equals((Map) that);
        return false;
    }

    public boolean equals(Map that) {
        if (that == null)
            return false;
        if (this == that)
            return true;

        boolean this_present_vals = true && this.isSetVals();
        boolean that_present_vals = true && that.isSetVals();
        if (this_present_vals || that_present_vals) {
            if (!(this_present_vals && that_present_vals))
                return false;
            if (!this.vals.equals(that.vals))
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetVals()) ? 131071 : 524287);
        if (isSetVals())
            hashCode = hashCode * 8191 + vals.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(Map other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.compare(isSetVals(), other.isSetVals());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetVals()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.vals, other.vals);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public _Fields[] getFields() {
        return _Fields.values();
    }

    public java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> getFieldMetaData() {
        return metaDataMap;
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("Map(");
        boolean first = true;

        sb.append("vals:");
        if (this.vals == null) {
            sb.append("null");
        } else {
            sb.append(this.vals);
        }
        first = false;
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class MapStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public MapStandardScheme getScheme() {
            return new MapStandardScheme();
        }
    }

    private static class MapStandardScheme extends org.apache.thrift.scheme.StandardScheme<Map> {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, Map struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // VALS
                        if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
                            {
                                org.apache.thrift.protocol.TMap _map46 = iprot.readMapBegin();
                                struct.vals = new java.util.HashMap<java.lang.Double, Double>(2 * _map46.size);
                                double _key47;
                                @org.apache.thrift.annotation.Nullable Double _val48;
                                for (int _i49 = 0; _i49 < _map46.size; ++_i49) {
                                    _key47 = iprot.readDouble();
                                    _val48 = new Double();
                                    _val48.read(iprot);
                                    struct.vals.put(_key47, _val48);
                                }
                                iprot.readMapEnd();
                            }
                            struct.setValsIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, Map struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.vals != null) {
                oprot.writeFieldBegin(VALS_FIELD_DESC);
                {
                    oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.DOUBLE, org.apache.thrift.protocol.TType.STRUCT, struct.vals.size()));
                    for (java.util.Map.Entry<java.lang.Double, Double> _iter50 : struct.vals.entrySet()) {
                        oprot.writeDouble(_iter50.getKey());
                        _iter50.getValue().write(oprot);
                    }
                    oprot.writeMapEnd();
                }
                oprot.writeFieldEnd();
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class MapTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public MapTupleScheme getScheme() {
            return new MapTupleScheme();
        }
    }

    private static class MapTupleScheme extends org.apache.thrift.scheme.TupleScheme<Map> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, Map struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetVals()) {
                optionals.set(0);
            }
            oprot.writeBitSet(optionals, 1);
            if (struct.isSetVals()) {
                {
                    oprot.writeI32(struct.vals.size());
                    for (java.util.Map.Entry<java.lang.Double, Double> _iter51 : struct.vals.entrySet()) {
                        oprot.writeDouble(_iter51.getKey());
                        _iter51.getValue().write(oprot);
                    }
                }
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, Map struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(1);
            if (incoming.get(0)) {
                {
                    org.apache.thrift.protocol.TMap _map52 = iprot.readMapBegin(org.apache.thrift.protocol.TType.DOUBLE, org.apache.thrift.protocol.TType.STRUCT);
                    struct.vals = new java.util.HashMap<java.lang.Double, Double>(2 * _map52.size);
                    double _key53;
                    @org.apache.thrift.annotation.Nullable Double _val54;
                    for (int _i55 = 0; _i55 < _map52.size; ++_i55) {
                        _key53 = iprot.readDouble();
                        _val54 = new Double();
                        _val54.read(iprot);
                        struct.vals.put(_key53, _val54);
                    }
                }
                struct.setValsIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

