/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package thrift.test;


public enum SomeEnum implements org.apache.thrift.TEnum {
    ONE(1),
    TWO(2);

    private final int value;

    private SomeEnum(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    @Override
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * @return null if the value is not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static SomeEnum findByValue(int value) {
        switch (value) {
            case 1:
                return ONE;
            case 2:
                return TWO;
            default:
                return null;
        }
    }
}
