/**
 * Autogenerated by Thrift Compiler (0.20.0)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package thrift.test;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class StringAndBinary implements org.apache.thrift.TBase<StringAndBinary, StringAndBinary._Fields>, java.io.Serializable, Cloneable, Comparable<StringAndBinary> {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("StringAndBinary");

    private static final org.apache.thrift.protocol.TField STRVAL_FIELD_DESC = new org.apache.thrift.protocol.TField("strval", org.apache.thrift.protocol.TType.STRING, (short) 1);
    private static final org.apache.thrift.protocol.TField BINVAL_FIELD_DESC = new org.apache.thrift.protocol.TField("binval", org.apache.thrift.protocol.TType.STRING, (short) 2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new StringAndBinaryStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new StringAndBinaryTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable java.lang.String strval; // optional
    public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer binval; // optional

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
        STRVAL((short) 1, "strval"),
        BINVAL((short) 2, "binval");

        private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

        static {
            for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
                byName.put(field.getFieldName(), field);
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByThriftId(int fieldId) {
            switch (fieldId) {
                case 1: // STRVAL
                    return STRVAL;
                case 2: // BINVAL
                    return BINVAL;
                default:
                    return null;
            }
        }

        /**
         * Find the _Fields constant that matches fieldId, throwing an exception
         * if it is not found.
         */
        public static _Fields findByThriftIdOrThrow(int fieldId) {
            _Fields fields = findByThriftId(fieldId);
            if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
            return fields;
        }

        /**
         * Find the _Fields constant that matches name, or null if its not found.
         */
        @org.apache.thrift.annotation.Nullable
        public static _Fields findByName(java.lang.String name) {
            return byName.get(name);
        }

        private final short _thriftId;
        private final java.lang.String _fieldName;

        _Fields(short thriftId, java.lang.String fieldName) {
            _thriftId = thriftId;
            _fieldName = fieldName;
        }

        @Override
        public short getThriftFieldId() {
            return _thriftId;
        }

        @Override
        public java.lang.String getFieldName() {
            return _fieldName;
        }
    }

    // isset id assignments
    private static final _Fields optionals[] = {_Fields.STRVAL, _Fields.BINVAL};
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

    static {
        java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
        tmpMap.put(_Fields.STRVAL, new org.apache.thrift.meta_data.FieldMetaData("strval", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
        tmpMap.put(_Fields.BINVAL, new org.apache.thrift.meta_data.FieldMetaData("binval", org.apache.thrift.TFieldRequirementType.OPTIONAL,
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING, true)));
        metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
        org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(StringAndBinary.class, metaDataMap);
    }

    public StringAndBinary() {
        this.strval = "";

        this.binval = java.nio.ByteBuffer.wrap("".getBytes());

    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public StringAndBinary(StringAndBinary other) {
        if (other.isSetStrval()) {
            this.strval = other.strval;
        }
        if (other.isSetBinval()) {
            this.binval = org.apache.thrift.TBaseHelper.copyBinary(other.binval);
        }
    }

    @Override
    public StringAndBinary deepCopy() {
        return new StringAndBinary(this);
    }

    @Override
    public void clear() {
        this.strval = "";

        this.binval = java.nio.ByteBuffer.wrap("".getBytes());

    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.String getStrval() {
        return this.strval;
    }

    public StringAndBinary setStrval(@org.apache.thrift.annotation.Nullable java.lang.String strval) {
        this.strval = strval;
        return this;
    }

    public void unsetStrval() {
        this.strval = null;
    }

    /** Returns true if field strval is set (has been assigned a value) and false otherwise */
    public boolean isSetStrval() {
        return this.strval != null;
    }

    public void setStrvalIsSet(boolean value) {
        if (!value) {
            this.strval = null;
        }
    }

    public byte[] getBinval() {
        setBinval(org.apache.thrift.TBaseHelper.rightSize(binval));
        return binval == null ? null : binval.array();
    }

    public java.nio.ByteBuffer bufferForBinval() {
        return org.apache.thrift.TBaseHelper.copyBinary(binval);
    }

    public StringAndBinary setBinval(byte[] binval) {
        this.binval = binval == null ? (java.nio.ByteBuffer) null : java.nio.ByteBuffer.wrap(binval.clone());
        return this;
    }

    public StringAndBinary setBinval(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer binval) {
        this.binval = org.apache.thrift.TBaseHelper.copyBinary(binval);
        return this;
    }

    public void unsetBinval() {
        this.binval = null;
    }

    /** Returns true if field binval is set (has been assigned a value) and false otherwise */
    public boolean isSetBinval() {
        return this.binval != null;
    }

    public void setBinvalIsSet(boolean value) {
        if (!value) {
            this.binval = null;
        }
    }

    @Override
    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
        switch (field) {
            case STRVAL:
                if (value == null) {
                    unsetStrval();
                } else {
                    setStrval((java.lang.String) value);
                }
                break;

            case BINVAL:
                if (value == null) {
                    unsetBinval();
                } else {
                    if (value instanceof byte[]) {
                        setBinval((byte[]) value);
                    } else {
                        setBinval((java.nio.ByteBuffer) value);
                    }
                }
                break;

        }
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public java.lang.Object getFieldValue(_Fields field) {
        switch (field) {
            case STRVAL:
                return getStrval();

            case BINVAL:
                return getBinval();

        }
        throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    @Override
    public boolean isSet(_Fields field) {
        if (field == null) {
            throw new java.lang.IllegalArgumentException();
        }

        switch (field) {
            case STRVAL:
                return isSetStrval();
            case BINVAL:
                return isSetBinval();
        }
        throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
        if (that instanceof StringAndBinary)
            return this.equals((StringAndBinary) that);
        return false;
    }

    public boolean equals(StringAndBinary that) {
        if (that == null)
            return false;
        if (this == that)
            return true;

        boolean this_present_strval = true && this.isSetStrval();
        boolean that_present_strval = true && that.isSetStrval();
        if (this_present_strval || that_present_strval) {
            if (!(this_present_strval && that_present_strval))
                return false;
            if (!this.strval.equals(that.strval))
                return false;
        }

        boolean this_present_binval = true && this.isSetBinval();
        boolean that_present_binval = true && that.isSetBinval();
        if (this_present_binval || that_present_binval) {
            if (!(this_present_binval && that_present_binval))
                return false;
            if (!this.binval.equals(that.binval))
                return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int hashCode = 1;

        hashCode = hashCode * 8191 + ((isSetStrval()) ? 131071 : 524287);
        if (isSetStrval())
            hashCode = hashCode * 8191 + strval.hashCode();

        hashCode = hashCode * 8191 + ((isSetBinval()) ? 131071 : 524287);
        if (isSetBinval())
            hashCode = hashCode * 8191 + binval.hashCode();

        return hashCode;
    }

    @Override
    public int compareTo(StringAndBinary other) {
        if (!getClass().equals(other.getClass())) {
            return getClass().getName().compareTo(other.getClass().getName());
        }

        int lastComparison = 0;

        lastComparison = java.lang.Boolean.compare(isSetStrval(), other.isSetStrval());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetStrval()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.strval, other.strval);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        lastComparison = java.lang.Boolean.compare(isSetBinval(), other.isSetBinval());
        if (lastComparison != 0) {
            return lastComparison;
        }
        if (isSetBinval()) {
            lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.binval, other.binval);
            if (lastComparison != 0) {
                return lastComparison;
            }
        }
        return 0;
    }

    @org.apache.thrift.annotation.Nullable
    @Override
    public _Fields fieldForId(int fieldId) {
        return _Fields.findByThriftId(fieldId);
    }

    public _Fields[] getFields() {
        return _Fields.values();
    }

    public java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> getFieldMetaData() {
        return metaDataMap;
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
        scheme(iprot).read(iprot, this);
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
        scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
        java.lang.StringBuilder sb = new java.lang.StringBuilder("StringAndBinary(");
        boolean first = true;

        if (isSetStrval()) {
            sb.append("strval:");
            if (this.strval == null) {
                sb.append("null");
            } else {
                sb.append(this.strval);
            }
            first = false;
        }
        if (isSetBinval()) {
            if (!first) sb.append(", ");
            sb.append("binval:");
            if (this.binval == null) {
                sb.append("null");
            } else {
                org.apache.thrift.TBaseHelper.toString(this.binval, sb);
            }
            first = false;
        }
        sb.append(")");
        return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
        // check for required fields
        // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
        try {
            write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
        try {
            read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
        } catch (org.apache.thrift.TException te) {
            throw new java.io.IOException(te);
        }
    }

    private static class StringAndBinaryStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public StringAndBinaryStandardScheme getScheme() {
            return new StringAndBinaryStandardScheme();
        }
    }

    private static class StringAndBinaryStandardScheme extends org.apache.thrift.scheme.StandardScheme<StringAndBinary> {

        @Override
        public void read(org.apache.thrift.protocol.TProtocol iprot, StringAndBinary struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TField schemeField;
            iprot.readStructBegin();
            while (true) {
                schemeField = iprot.readFieldBegin();
                if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
                    break;
                }
                switch (schemeField.id) {
                    case 1: // STRVAL
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.strval = iprot.readString();
                            struct.setStrvalIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    case 2: // BINVAL
                        if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                            struct.binval = iprot.readBinary();
                            struct.setBinvalIsSet(true);
                        } else {
                            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                        }
                        break;
                    default:
                        org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
                }
                iprot.readFieldEnd();
            }
            iprot.readStructEnd();

            // check for required fields of primitive type, which can't be checked in the validate method
            struct.validate();
        }

        @Override
        public void write(org.apache.thrift.protocol.TProtocol oprot, StringAndBinary struct) throws org.apache.thrift.TException {
            struct.validate();

            oprot.writeStructBegin(STRUCT_DESC);
            if (struct.strval != null) {
                if (struct.isSetStrval()) {
                    oprot.writeFieldBegin(STRVAL_FIELD_DESC);
                    oprot.writeString(struct.strval);
                    oprot.writeFieldEnd();
                }
            }
            if (struct.binval != null) {
                if (struct.isSetBinval()) {
                    oprot.writeFieldBegin(BINVAL_FIELD_DESC);
                    oprot.writeBinary(struct.binval);
                    oprot.writeFieldEnd();
                }
            }
            oprot.writeFieldStop();
            oprot.writeStructEnd();
        }

    }

    private static class StringAndBinaryTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
        @Override
        public StringAndBinaryTupleScheme getScheme() {
            return new StringAndBinaryTupleScheme();
        }
    }

    private static class StringAndBinaryTupleScheme extends org.apache.thrift.scheme.TupleScheme<StringAndBinary> {

        @Override
        public void write(org.apache.thrift.protocol.TProtocol prot, StringAndBinary struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet optionals = new java.util.BitSet();
            if (struct.isSetStrval()) {
                optionals.set(0);
            }
            if (struct.isSetBinval()) {
                optionals.set(1);
            }
            oprot.writeBitSet(optionals, 2);
            if (struct.isSetStrval()) {
                oprot.writeString(struct.strval);
            }
            if (struct.isSetBinval()) {
                oprot.writeBinary(struct.binval);
            }
        }

        @Override
        public void read(org.apache.thrift.protocol.TProtocol prot, StringAndBinary struct) throws org.apache.thrift.TException {
            org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
            java.util.BitSet incoming = iprot.readBitSet(2);
            if (incoming.get(0)) {
                struct.strval = iprot.readString();
                struct.setStrvalIsSet(true);
            }
            if (incoming.get(1)) {
                struct.binval = iprot.readBinary();
                struct.setBinvalIsSet(true);
            }
        }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
        return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
}

