name: Build Artifact

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build package
        run: mvn --batch-mode clean verify

      - name: Codecov
        uses: codecov/codecov-action@v2
